pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t bharu2003/devops:v1 .'  
                }
            }
        }
        
        stage('Push') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub-credentials', variable: 'DOCKERHUB_PASS')]) {
                        sh 'docker login -u bharu2003 -p $Bharu@2003' 
                        sh 'docker push bharu2003/devops:v1'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f k8s/service1-deployment.yaml'
                    sh 'kubectl apply -f k8s/service1-service.yaml'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker rmi bharu2003/devops:v1' 
        }
    }
}
